apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-app
  labels:
    app: ignite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ignite-app
  template:
    metadata:
      labels:
        app: ignite-app
    spec:
      containers:
      - name: ignite-app
        image: ileriayo/ignite:latest
        ports:
        - containerPort: 3000